version: 0.0
os: linux
files:
  - source: /
    destination: /var/aleksnweb/
hooks:
  ApplicationStart:
    - location: scripts/appstart.sh
      timeout: 30
      runas: root
  ApplicationStop:
    - location: scripts/appstop.sh
      timeout: 30
      runas: root